<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8"/>
		<title>Slim 3</title>
		<link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
		<style>
			body {
				margin: 50px 0 0 0;
				padding: 0;
				width: 100%;
				font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
				text-align: center;
				color: #aaa;
				font-size: 18px;
			}

			h1 {
				color: #719e40;
				letter-spacing: -3px;
				font-family: 'Lato', sans-serif;
				font-size: 100px;
				font-weight: 200;
				margin-bottom: 0;
			}
		</style>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	</head>
	<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="#">認証サンプル</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/">登録 <span class="sr-only"></span></a></li>
        <li><a href="#">Link</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/login">Login</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>