<?php include 'header.phtml'?>
		<form action="/login" method="post">
			<h1>ログイン</h1>
			<div class="form-group">
					<label for="email">email</label>
					<input type="email" name="email" id="email" value="" required>
		    </div>
            <div class="form-group">
                <label for="password">password</label>
                <input type="password" name="password" id="password" value="" required>
            </div>
            <div class="form-group">
                <input type="submit">
            </div>
		</form>
<?php include 'footer.phtml'?>
